version: 2
jobs:
  general-check:
    docker:
      - image: circleci/node:11.2.0-stretch-browsers

    steps:
      - checkout

      - run: git fetch origin

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      #Run lint
      - run: yarn tslint

      # Run test
      # - run: yarn test
      # Run build
      # - run: yarn build

workflows:
  version: 2
  build_and_test:
    jobs:
      - general-check
      # - creator-build:
      #     requires:
      #       - tslint-build
      #     filters:
      #       branches:
      #         only: master
